### ISSUE TITLE
Busy-wait spinner disappears too soon

### ISSUE THREAD

**Issue by susanev** [chef/automate#1062]
_Originally reported by @msorens_

## Problem
Users do not have a clear and consistent experience related to data loading onto the page. This also causes some side effects of blinking/flashing which is a poor experience and inaccessible. Users can also be presented with incorrect information before the page finishes loading.

## Desired Experience
The content loading overlay is displayed on any page that has slow loading. Users can view data being populated behind the modal (by way of opacity). All content should be loaded fully (and sorted) before the loading modal is dismissed.

## Subtasks Slash Inventory of Tables
- [x] tokens list ([/settings/tokens](https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/tokens))
- [ ] projects list ([/settings/projects](https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/projects))
- [ ] policies list ([/settings/policies](https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/teams))
- [ ] teams list ([/settings/teams](https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/teams))
- [ ] users list ([/settings/users](https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/users))
- [ ] roles list ([/settings/roles](https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/roles))
- [ ] adding users to teams ([/settings/teams/id/add-users](https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/teams/admins/add-users))
- [ ] adding members to policies  ([/settings/policies/id/add-members](https://a2-local-inplace-upgrade-acceptance.cd.chef.co/settings/policies/administrator-access/add-members))

## Repro

[Video](https://drive.google.com/open?id=16hwXlKqNIYFjQ-3IrBiyHnQnKaRTKvj-)

It turns out that if you have a lot of things (tokens, users, teams, etc.) then the busy-wait spinner disappears before the data on the page renders--sometimes a long time before.

I first noticed this in acceptance testing on `https://a2-local-inplace-upgrade-acceptance.cd.chef.co/`, which had on the order of a hundred tokens. The delay between the spinner disappearing and the tokens displaying was not long, but noticeable, from a half-second to perhaps 2 seconds.

I then set about to reproduce this on my own box, first creating a token generator:

```
a2TokenFactory() {
  default_token_mode=create
  default_count=5
  token_mode=${1:-$default_token_mode}
  count=${2:-$default_count}
  id_prefix=test-token-1111

  if [[ $token_mode == create ]]; then
    echo "Creating $count tokens..."
    for (( i = 1; i <= $count; i++ )) 
    do
      jo -p id="$id_prefix-$i" name="$id_prefix $i" active=true | curl -sSkH "api-token: $TOK" $TARGET_HOST/apis/iam/v2beta/tokens -X POST --data @- > /dev/null
    done
  elif [[ $token_mode == delete ]]; then
    echo "Removing $count tokens..."
    for (( i = 1; i <= $count; i++ )) 
    do
      curl -sSkH "api-token: $TOK" $TARGET_HOST/apis/iam/v2beta/tokens/$id_prefix-$i -X DELETE > /dev/null
    done
  else
    echo 'usage: a2TokenFactory ( create | delete ) ( count )'
    echo 'default: a2TokenFactory create 5'
  fi
}
```

I then created 500 tokens... 

```
a2TokenFactory create 500
```

and artificially slowed down my network using Chrome dev tools.

The first time I clicked on tokens the gap was just a few seconds. But then clicking away, e.g. to Teams, then back to Tokens, the delay was, well.... watch the video:

So the issue is that we are storing in ngrx state (a) the status that data is available at the same time (indeed, in the same call) that (b) the data itself. The problem is that the page rendering starts to react to both at the same time and, naturally, it is much quicker to react to a single boolean state value than it is to react to a large array of objects that need to be rendered in a table.

So I explored this a bit on StackOverflow: [Finer control over angular rendering](https://stackoverflow.com/questions/54937329/finer-control-over-angular-rendering) and was advised of a hook I was looking for that might help... alas, tried it briefly, but no joy!

By the way, all those tokens can be cleaned up with:

```
a2TokenFactory delete 500
```

**Comment by srenatus** [comment]
Meta: what a great issue. :100:

**Comment by srenatus** [comment]
A few thoughts here:

- Our token APIs for _listing tokens_ are an all-or-nothing affair: they don't support pagination. If there was a way to request as many tokens as you want to render **only**, the delay would probably be less noticable.
  - On a related note, **at some point**, the "return all tokens at once" will hit GRPC's message limit of 4Mb. It could be that this never happens in the real world, but it's a theoretical possibility.
- Another speed-related matter is that all token-related read requests (Get and List) are fulfilled by asking the database. `authn-service`, which offers the API to manage tokens, could cache them in memory and serve the requests from there. I'm not sure how this would impact _this issue_, though. However, since for API requests (data ingestion), the same database roundtrip happens, it could be worthwhile to look into this. We know that pg can become a bottleneck for giant deployments, I think.

**Comment by msorens** [comment]
On your first point, @srenatus, yes for pagination! That would completely alleviate this issue.
On your second point--I'm sure you know but for others following along just want to be explicit--back-end speed performance is important, but unrelated. It would not affect this particular issue one way or the other.

**Comment by blakestier** [comment]
We're also seeing the spinner go away too soon (if it appears at all) when attempting to add users on a team. The page flickers while it loads a list of users, modifies and sorts those users. We should have a spinner up while that happens.

**Comment by sdelano** [comment]
Step 1 when for when we start the first sprint on Monday will be to investigate each of the cases above and gather more information about where we need to make the changes.
