### ISSUE TITLE
add IdP configuration integration tests

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1093]
## User Story

As a Developer, I will use this work when I want to ensure different IdP configurations work as expected.

## Definition of Done
we have integration tests covering each of the IdP configuration combinations:
- none (only local)
- LDAP
- SAML
- LDAP and SAML
- MSAD and SAML

## Demo Script / Repro Steps
- run tests as part of our automated pipeline

## Sub-tasks
- [ ] set up an openLDAP instance (or use another LDAP service we operate) and configure one of our dev/acceptance environments with SAML to use it 
- [ ] use an MSAD service we operate and configure one of our dev/acceptance environments with SAML to use it 
- [ ] write integration tests that log in using each configured IdP

**Comment by srenatus** [comment]
As per @jaym's helpful [slack messages here](https://chefio.slack.com/archives/C61F9HHKK/p1565699604435200), this is what we could do to add openldap into our CI integration test system:

**Either**
- create a new test like [`integration/tests/ha_chef_server.sh`](https://github.com/chef/automate/blob/master/integration/tests/ha_chef_server.sh) that uses docker in the tests directly;

**or**
- use the "external services" bits for creating a new one: [`integration/services`](https://github.com/chef/automate/tree/master/integration/services), and use it like this: [`integration/tests/ha_data_services.sh#L5`](https://github.com/chef/automate/blob/master/integration/tests/ha_data_services.sh#L5).

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
