### ISSUE TITLE
Remove the data-lifecycle-service

### ISSUE THREAD

**Issue by ryancragun** [chef/automate#1181]
Rather than having an entire service that's sole purpose is making scheduled gRPC calls to various services, we'll remove the data-lifecycle-service and move all scheduled `Purge` jobs to cereal workflows in the services themselves.

Currently there are three services that implement the data lifecycle management interface and rely on the data-lifecycle-service to purge data: 
* ingest-service
* compliance-service
* event-feed

All will need to be migrated to cereal workflows in order to remove the data lifecycle service

### Tasks
- [x] Migrate ingest-service time series purging to cereal workflows.
- [x] Delete data-lifecycle-service
- [x] Update deployment-service to no longer start data-lifecycle-service
- [x] Deprecate data lifecycle config for data-lifecycle-service, ingest-service, event-feed-service and compliance-service
- [x] Migrate the compliance data-lifecycle manageable interface to a cereal workflow.
- [x] Migrate event-feed manageable interface to a cereal workflow.
- [x] Delete data-lifecycle interservice protobufs
