### ISSUE TITLE
Auth form input issues

### ISSUE THREAD

**Issue by srenatus** [chef/automate#1185]
## Problem
Humans are often frustrated by filling out forms that throw errors before they have been able to provide any information and by the content being hidden on the page.

## Overivew

A few auth input issues to fix, (1) stop presenting an error on the password field before the user has a chance to provide one, (2) stop the browser from showing the auto-complete box and (3) give the user a chance to provide an ID before presenting them with an error.

#### To Reproduce
- Go to Settings > Users
- Click _Create User_
- Observe the form:

![image](https://user-images.githubusercontent.com/870638/62605304-1844af00-b8fa-11e9-8c60-0fe376d5bddb.png)

#### Expected behavior

There's no error below _Password_

#### Details
* Set auto-complete to `off` on inputs
* Reference: [Removing the browser's built-in auto-complete feature](https://github.com/chef/automate/pull/1095)

![auth-complete-fun](https://user-images.githubusercontent.com/5489125/62654616-0de3de80-b915-11e9-9d6b-795f7b4a6691.png)

#### Expected behavior

There is no auto-complete box.

#### To Reproduce
- Navigate to `Settings > Teams > Create Team`, `Settings > API Tokens > Create Token`, or `Settings > Projects > Create Projects`
- Use the _Edit ID_ button
- Observe an error

![id-error](https://user-images.githubusercontent.com/5489125/62654716-3f5caa00-b915-11e9-8174-1fb2474ea45b.png)

#### Expected behavior

There's no error below _ID_

## Subtasks
- [x] Fix password error #1190 @msorens 
- [ ] Turn off auto-complete *RFR* #1195
- [ ] Fix ID error *RFR* #1195

## Notes
ℹ️ Both in `dev` and `acceptance` as of 08/06.

**Comment by susanev** [comment]
@srenatus i hijacked this issue and added a few more issues to it, hope you don't mind ✌️
