### ISSUE TITLE
Add more features to _Data Lifecycle_

### ISSUE THREAD

**Issue by susanev** [chef/automate#1208]
## Overview
Thanks to the 🥣 work by the deployment team we are able to add the rest of the settings into the _Data Lifecycle_ page without causing any service restarts. Note, this page is currently called _Node Lifecycle_ but will be adjusting to _Data Settings_. If any questions come up with how to connect to the backend please reach out to @danielsdeleo and @ryancragun.

If possible, connect with @susanev for a walkthrough before starting work on this issue, please and thank you.

## Design Details
[UX Designs in Abstract](https://share.goabstract.com/47da49f4-55df-4be0-be66-018952857ae3?mode=design&sha=84902a48f104fe6bb5f4cefa3754cc83a72ccbe0)

### Settings Left-Nav Updates
- [x] add new _General Settings_ heading, please use text-transform for the casing
- [x] move _Node Lifecycle_ up to that section and rename it to _Data Lifecycle_
- [x] move _Notifications_ up below _Data Lifecycle_

### Page Content
- [x] heading: Data Lifecycle
- [x] subheading: Manage the retention of events, service groups, Chef Client runs, compliance reports and scans in Chef Automate.
- [x] other headings on the page are `font-size: 16px; font-weight: 600`; and should be h2s semantically

#### Interaction Patterns
- On _check_ the inputs should become enabled and the defaults should be filled in
- On _uncheck_ the inputs should become disabled with whatever last value they held; `background-color: #E6EBEE;` and `opacity: 0.5;`
- Primary, _Save Changes_ button should be disabled until a change is made to a checkbox or an input it should then become enabled; on action its disabled with the label \<loading spinner\>_Saving..._; after saved the button returns to disabled and _Save Changes_ 
- All number inputs should be restricted to only accept integer values greater than zero
- Checking or unchecking a parent checkbox should have no effect on its visual child

#### Event Feed
- _Remove event feed data after_
    - default: enabled, 30 days
- _Remove Chef Server actions after_
    - default: enabled, 30 days

#### Service Groups
- [x] This section should be completely hidden unless the `EAS Applications` ui feature flag has been turned on
- _When no health check reports have been received for a service in \<n time\>, label the service as disconnected_ 
    - This checkbox is a special case and should be presented as disabled to prevent the user from being able to turn it off, but note that it is possible to turn it off from the api, if that happens it should remain disabled but be shown as an unchecked checkbox with disabled number and time type inputs
    - default: 5 minutes
- _Remove services labeled as disconnected after_
    - default: enabled, 7 days

#### Client Runs
- _Remove data for Chef Client runs after_
     - default: enabled, 30 days
- _When no Chef Client run data has been received from a node in \<n time\>, label the node as missing_
    - default: enabled, 30 days
- _Remove nodes labeled as missing after_; default: enabled, 30 days

#### Compliance
- _Remove compliance reports after_
    - default: disabled
    - if enabled default to 30 days
- _Remove compliance scans after_
    - default: disabled
    - if enabled default to 30 days

### Visual Design
- [x] h2s are `font-size: 16px; font-weight: 600;`
- [x] 8px of space on either side of the inputs in the checkbox text
- [x] 12px between checkbox rows
- [x] 30px between sections
~75px between the last section and the save button~
- [x] Move Save button to the top, left-aligned
- [x] indented checkboxes are 69px from the left-nav
- Disabled checkbox has `background-color: #E6EBEE; opacity: 0.5;` if its checked a #fff check should be shown, if unchecked then no check should be shown
- +1: Change background of main page

## Documentation Updates
_Updates to the [Node Lifecycle](https://automate.chef.io/docs/node-lifecycle/) page_
- Change the route to `data-lifecycle`
- Change the page title to _Data Lifecycle_
- Add sections for _Event Feed_, _Service Groups_, _Client Runs_, and _Compliance_ along with some content
- A single screenshot, or screenshots for each section whichever docs prefer

**Comment by susanev** [comment]
@susanev will add details about feature flags and services stuff

**Comment by danielsdeleo** [comment]
I have some examples of usage of the APIs for configuring the services lifecycle things on this PR: https://github.com/chef/automate/pull/1443
