### ISSUE TITLE
Final cleanup migration to delete IAMv1 data

### ISSUE THREAD

**Issue by susanev** [chef/automate#1452]
## Subtasks
- [ ] Rename token database column`description` to `name`
- [ ] Migrate user_team_assocation table to replace v1 user GUIDS with v2 user IDs.
- [ ] Update UI to use User v2 IDs as input into Teams membership APIs from membership_id. (remove VersionizeTeam helpers, etc)
- [ ] Remove the membership_id field from the Users API.
- [ ] **save this for last**: update authz tables by dropping `policies`
```
 Schema |                  Name                   |   Type   | Owner 
--------+-----------------------------------------+----------+-------
 public | policies                                | table    | authz
```

**Comment by bcmdarroch** [comment]
all of these are addressed across these issues:
teams & users: https://github.com/chef/automate/issues/1144
tokens: https://github.com/chef/automate/issues/2741
policies: https://github.com/chef/automate/issues/2739
