### ISSUE TITLE
Re-enable authz integration tests against a running automate instance

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#1607]
## Description

As part of the cereal work, we commented out some of our integration tests because mocking cereal would have been a challenge.

We should get those tests passing again. The path forward is to get rid of all of the places the integration tests are using are artisanal setup in testhelpers.go and actual run all the go integration tests against a running instance of automate so we don't have to mock anything (i.e. the studio, in CI etc).

## Definition of Done

All commented tests are passing.

## Subtasks

- [ ] Identify test breakup and move unit tests @tylercloke 
- [ ] Move remaining tests to integration tests
- [ ] Decide what to do with any remaining tests

**Comment by bcmdarroch** [comment]
This issue is focused on the commented out tests in [system integration tests](https://github.com/chef/automate/blob/master/components/authz-service/server/v2/system_integration_test.go#L61-L717).

1. We should port as many of the commented out tests as possible to our Cypress API test suite.

2. We should come up with a plan for any tests that can't be ported over (i.e. must use a mocked error response from Cereal). Those may need to be moved to a new file that specifically tests authz and cereal integration. System integration test has historically only been used for OPA and authz integration testing.

**Comment by tylercloke** [comment]
https://chefio.slack.com/archives/C61F9HHKK/p1576854825040600
