### ISSUE TITLE
Consistent date/time across Automate

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#1645]
## Problem
We do not have a consistent date/time pattern across Automate which makes it a confusing experience. Currently, dates are also US-centric which is confusing for folks outside the US.

## Goal
Consistent date/time display across automate, that displays the day of the month, before the month.

## Overview
Currently, the date/time format on some pages does not match the consistency pattern we have developed. Specifically, it should be displayed as...
`<Day of week:word as abbreviation>, <Day: num, prepend w/ 0> <Month:word as abbreviation> <Year: num> <Time: 00:00:00> UTC`
e.g., `Wed, 03 Jul 2019 17:08:53 UTC`

## Checklist
- [x] api tokens #1690 
- [x] node integrations #1690
- [x] node credentials #1690
- [x] license trial applied modal #1689  
- [x] license lockout modal #1689
- [x] client runs node detail #1823
- [x] run history panel #1865
- [x] compliance reports #1821
- [x] compliance repots detail page #1821
- [x] client run and compliance exports #1983
- [x] compliance reporting calendar #2048 (in acceptance)
- [x] scan job schedule input #2048 (in acceptance)
- [x] event feed guitar strings (in dev)
- [x] event feed event list (in dev)
- [x] event feed side panel (in dev)

#### Client runs node detail
<img width="1094" alt="client runs node detail" src="https://user-images.githubusercontent.com/10341541/65105549-85843f00-d992-11e9-948d-2c6972a5575a.png">

#### Run history panel
<img width="431" alt="run history panel" src="https://user-images.githubusercontent.com/10341541/65105550-85843f00-d992-11e9-81ec-3e86c594b037.png">

#### Compliance reports
<img width="1077" alt="compliance reports" src="https://user-images.githubusercontent.com/10341541/65105551-861cd580-d992-11e9-8638-ae0bfb1a2710.png">

#### Compliance reports detail page
<img width="1095" alt="compliance reports detail page" src="https://user-images.githubusercontent.com/10341541/65105552-861cd580-d992-11e9-9d65-805fbefc25be.png">

#### Node integrations
<img width="1091" alt="node integrations" src="https://user-images.githubusercontent.com/10341541/65105553-861cd580-d992-11e9-86c1-5a7e6b6fafea.png">

#### Node credentials
<img width="1095" alt="node credentials" src="https://user-images.githubusercontent.com/10341541/65105554-861cd580-d992-11e9-81c9-1bb6aae000ed.png">

Aha! Link: https://chef.aha.io/epics/A2-E-166

**Comment by jonong1972** [comment]
The EAS team has also been working on time formats here:
https://github.com/chef/automate/pull/786

We should sync up and get all on the same page with them. Possibly use the same date/time component?

**Comment by vjeffrey** [comment]
let's all chat about this in the automate-leads mtg?

**Comment by danielsdeleo** [comment]
![screenshot of API Tokens page](https://user-images.githubusercontent.com/37162/65278285-a35fba00-dae0-11e9-8f12-f847bee57307.png)

**Comment by susanev** [comment]
#1678 1678

**Comment by susanev** [comment]
and here is one for the trial license modal #1679
