### ISSUE TITLE
Allow Admin to Configure Project Limit

### ISSUE THREAD

**Issue by susanev** [chef/automate#1840]
## Story

As a developer of Automate - I want to be able to increase the default limit on projects so that I can develop a better UI quickly and test the scaling of projects.

As a user of IAM with Projects - I want to be able to configure the project limit so that I can exceed six projects. I understand that if I do so that I may run into issues in the UI where things don't visually scale or where there may be usability issues.

## Experience

Config:

```cat <<EOF > authz.toml
[auth_z.v1.sys.service]
project_limit = 7
EOF
```
`chef-automate config patch authz.toml`

Attempt to make more than 7 custom projects 💁(`curl -XPOST -d '{"name":"test", "id":"foo1-project"}' -H "api-token: $TOK" $TARGET_HOST/apis/iam/v2beta/projects --insecure`)

*Caveats*:
- UI will still be limited to creating 6 projects and any text about the limit will show up there.
  - We *could* expose an API that hinted to the UI what the limit is, but since this is a temporary we're going to live with the UI showing the lower limit and any users will need to use the API to create projects.

*Known Issues*:
- Projects list page takes ~15 seconds to load (we make a introspection call for each project)

## Overview
- expose the project limit so that an admin can change it to whatever they want
- we can communicate to potential users of this that the projects list page will be very slow
  - we should also investigate other areas where performance might be impacted
- this is to unblock folks as soon as possible, we will then be fixing the ui issues
- chef-automate config value

## Implementation
Places we need changes:
- [x] `api/config/authz/*.proto` to add the config
- [x] config validation that the limit is greater than (or equal to) 6
- [x] write to config file via hab template in `components/authz-service/habitat/config/config.yml`
- [x] value read out of config at startup and passed via struct to postgres code
- [ ] update our internal acceptance environments to have a larger limit than 6
- [ ] delete the code from the UI that limits projects to 6, theres a sentence in the subheading and the disabling of the create button.. remove those.

Subtasks:

- [x] Add option to configure via toml @blakestier #2029 _merged_
- [x] Remove projects limiting logic/text from UI @blakestier #2049 _merged_
- [ ] Update internal acceptance envs to allow more than 6 @bcmdarroch #2051 _ready for review_

**Comment by susanev** [comment]
as a note i was able to get scrollbars added to both project dropdowns, so the ui will be slow but usable when people increase #1956

**Comment by susanev** [comment]
@sdelano see my note above, the scrollbars have already been added (in dev currently)
