### ISSUE TITLE
Auto-generate policies when project is created

### ISSUE THREAD

**Issue by susanev** [chef/automate#1848]
## Overview
When a project is created, automatically create `<project-name>-project-owner`, `<project-name>-editor`, and `<project-name>-viewer` policies. The policies should leverage the associated roles, and automatically add the project id on the policy and the statement.

Generating these policies will take care of a lot of rote tasks for the administrator.

## Design Details
- The create project modal should have a checkbox input added below the ID field
    - 30px of space between this checkbox and the ID
    - 38px of total space between the checkbox and the buttons (30 px from the margin bottom on the checkbox, 8px of top margin on the buttons)
    - checked by default, and disabled since the user will not be able to stop this from happening until after ga
    - checkbox text is... `Also create owner, editor, and viewer policies for this project.`

### Checked and Disabled
![create-project-with-disabled-checkbox](https://user-images.githubusercontent.com/5489125/67797418-eea1ac80-fa3e-11e9-8265-46cd352cc979.png)

## Subtasks

**Note**: any of these subtasks may be combined into one PR if that is preferred

- [ ] on each CreateProject API call, upon successful creation of the project, create a Project Owner policy like the following:
```
{
   "name": "<new-project-id> Project Owners",
   "id": "<new-project-id>-project-owners",
   "projects": ["<new-project-id>"],
   "members": [],
   "statements": [
     {
       "effect": "ALLOW",
       "role": "project-owner",
       "projects": [
         "<new-project-id>"
       ]
     }
   ]
 }
```
- [ ]  on each CreateProject API call, upon successful creation of the project and the Project Owner policy, create a Project Editor policy like the following:
```
{
   "name": "<new-project-id> Project Editors",
   "id": "<new-project-id>-project-editors",
   "projects": ["<new-project-id>"],
   "members": [],
   "statements": [
     {
       "effect": "ALLOW",
       "role": "editor",
       "projects": [
         "<new-project-id>"
       ]
     }
   ]
 }
```
- [ ] on each CreateProject API call, upon successful creation of the project and the previous 2 policies, create a Project Viewer policy like the following:
```
{
   "name": "<new-project-id> Project Viewers",
   "id": "<new-project-id>-project-viewers",
   "projects": ["<new-project-id>"],
   "members": [],
   "statements": [
     {
       "effect": "ALLOW",
       "role": "viewer",
       "projects": [
         "<new-project-id>"
       ]
     }
   ]
 }
```
**Note:** if any policy fails to be created, the entire project creation request is rolled back. the user must try to create the project again

**Comment by sdelano** [comment]
Should this also include teams or do we have a separate story for that?

**Comment by susanev** [comment]
@sdelano we cut _teams_ from this for ga, i will make a separate card for post ga.

**Comment by susanev** [comment]
#1882

**Comment by susanev** [comment]
@msorens @bcmdarroch ive added the ux content needed for this issue, if either of you have feedback please let me know.

**Comment by susanev** [comment]
ill update the ui content and screenshots by end of day today.

**Comment by susanev** [comment]
@bcmdarroch @msorens updated again after planning convo, opting for making the checkbox disabled for now since they wont have the option to not create policies until after ga.
