### ISSUE TITLE
force upgrade to IAM v2

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#1879]
## User Story

As a customer on IAM v1, as soon as I update Automate to the release with the force upgrade, I will be on IAM v2, with both role-based access and project filtering available for me to use. 

As a customer already on IAM v2, I will already be on IAM v2.1 as of the v2.1 beta release. 

I will no longer be able to change the IAM version. The commands `chef-automate iam reset-to-v1` and `chef-automate iam upgrade-to-v2` are no longer available

## Definition of Done
- [x] only use IAM v2 middleware gateway
- [x] authz database's IAM migration status should be set to `SuccessBeta1`
- [x] remove the CLI commands `chef-automate iam reset-to-v1` and `upgrade-to-v2`.
    - [x] remove CLI commands from documentation
- [x] remove any integration scripts that depend on `chef-automate iam reset-to-v1`, i.e. the  [upgrade-reset integration test](https://github.com/chef/automate/blob/master/integration/tests/upgrade_reset_iam_v2.sh)

## Demo Script / Repro Steps
1. Start on a version of Chef Automate that uses IAM v1. Upgrade Chef Automate to a version that forces the upgrade. Everything should be migrated to IAM v2.1.
2. Start on a version of Chef Automate (non-force upgrade) that uses IAM v2.1. Upgrade Chef Automate to a version that forces the upgrade. There should be no error since you're on IAM v2.1
3. In either case, should not be able to run `chef-automate iam reset-to-v1`. This command should no longer exist in the CLI. If a user is using an old version of the CLI, the gRPC endpoints that the CLI calls should not exist.

**Comment by sdelano** [comment]
**Notes 2020-01-27**

* IAMv1 Support: recommended path is to upgrade to IAMv2
  * we will be able to deploy old versions of automate for testing and reproduction of migration and upgrade issues
* things to delete:
  * IAMv1 APIs (third)
    * and tests
    * understand implications of deep upgrade tests
  * auth middleware
    * delete the v1 pieces of auth interceptor (gateway)
    * unconditionalize the v2 pieces
  * v1/v2 conditional logic
    * API
    * UI (fourth)
    * interceptor code on authz service
  * CLI migration / upgrade command (second priority)
    * (keep the `chef automate iam version` command) 
  * migration plumbing and tracking for v2 goes away and moves into the go migrate library
* [ ] card to track the testing of the upgrade
* rewrite migrations (look at all the things in upgrade-to-v2 command) (top priority)
  * v1 policies
  * create initial teams
  * update iam version database number
* tech debt
  * special casing in the UI to convert v1 teams objects to v2 style
  * calling the v2 API
