### ISSUE TITLE
data feed ui consistency updates

### ISSUE THREAD

**Issue by susanev** [chef/automate#2098]
## Overview
The new data feed page needs to be updated to be consistent with the rest of Automate.

## Setup steps
To see data feeds in the settings section, type `feat` on any page to open the feature flags and then turn on the service now feature flag.

## General
- change data feeds left-nav icon to `assignment`
- change h1 to _Data Feeds_
- note: subheading will be changed, but i dont have that content yet, ping me for it when this has a pr

### Empty state
- change empty message to _Create a data feed to get started!_
-  change primary button to _Create Data Feed_

#### Screenshot
![create-data-feed-empty-state](https://user-images.githubusercontent.com/5489125/68089899-72361180-fe22-11e9-9564-b0c4939b960f.png)

### Data feed list
- change primary button to _Create Data Feed_
- change only column header to _Name_
- change control menu option to _Delete Data Feed_ and add an option for _Test Data Feed_ above it
- on delete use the same delete confirmation modal as api tokens, along with on-page notification after delete

##### List page
![data-feed-list-page](https://user-images.githubusercontent.com/5489125/68089914-9396fd80-fe22-11e9-9b8e-fabc33b927c8.png)

##### Control menu and delete confirmation
![data-feed-control-menu](https://user-images.githubusercontent.com/5489125/68168791-de963b00-ff1e-11e9-8c60-780ea4793eff.png)

![data-feed-list-page-delete-modal](https://user-images.githubusercontent.com/5489125/68090054-4f0c6180-fe24-11e9-8e78-92df8672850c.png)

### Create modal
- change the pattern to use the on-page create modal (see api tokens for example)
- form items are..
    - Name
    - URL
    - Username
    - Password
- 3 buttons: _Create Data Feed_ (primary), _Test Data Feed_ (secondary), _Cancel_ (tertiary)
- feedback from the data feed test button should be displayed on the modal above the buttons as shown in the screenshots
- after save on create modal there should be an on page notification

##### Blank
![create-data-feed-data](https://user-images.githubusercontent.com/5489125/68089933-c93be680-fe22-11e9-9c98-c0c11a567fe4.png)

##### Error after send test
![create-data-feed-data-after-test-failed](https://user-images.githubusercontent.com/5489125/68089952-fe483900-fe22-11e9-930e-17811da09c13.png)

##### Success after send test
![create-data-feed-data-after-test-success](https://user-images.githubusercontent.com/5489125/68089956-02745680-fe23-11e9-8c63-be1aadb4b75c.png)

##### After create
![data-feed-list-create-notification](https://user-images.githubusercontent.com/5489125/68089985-7dd60800-fe23-11e9-863d-9bddac405eb4.png)

### Detail page
- use the same design patterns as api tokens
- breadcrumb, heading, labels, etc
- on change save button should become endabled
- after save the button should become disabled with a message _All changes saved._ next to it
- test button should produce on page notifications

##### Page
![data-feed-detail-page](https://user-images.githubusercontent.com/5489125/68089999-aeb63d00-fe23-11e9-8586-1a7b741dfc44.png)

##### Fail test notification
![data-feed-detail-page-test-fail-notification](https://user-images.githubusercontent.com/5489125/68091730-4756b800-fe38-11e9-88a8-0f5ea0cc15ad.png)

##### Success test notification
![data-feed-detail-page-test-success-notificatio](https://user-images.githubusercontent.com/5489125/68091731-4a51a880-fe38-11e9-979a-dd59dcf1e3d4.png)
**sub-tasks**
- [x] https://github.com/chef/automate/issues/2745

- [ ] https://github.com/chef/automate/issues/2746

- [ ] https://github.com/chef/automate/issues/2760
