### ISSUE TITLE
add filter button to controls

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#26]
# User Story

In today's version of Automate, we have these handy-dandy filter buttons on the nodes list and profiles list.

Example:
<img width="849" alt="Screen Shot 2019-04-10 at 19 24 49" src="https://user-images.githubusercontent.com/10341541/55924252-55a46480-5bc6-11e9-90d7-8b08f6b15669.png">
the filter button is the one just to the left of the scan results button.

With the (soon-arriving) addition of deep filtering, we expect that more users will want to filter by control. Instead of making them type up the control every time, we could add the same filter button to the places in the ui where we list controls.
Those are:
 - [ ] scan results (accessible from reporting nodes list and reporting profiles list)
 - [ ] reporting profile details (accessible by clicking on a profile in reporting profiles list)
 - [ ] reporting node details (accessible by clicking on a node in reporting nodes list)

**required: ux designs**

# Definition of Done
filter buttons on all control lists

Aha! Link: https://chef.aha.io/epics/SH-E-459

**Comment by vjeffrey** [comment]
this whole thing should be made easier by the controls list work

**Comment by jonong1972** [comment]
For the sake of getting this enhancement out, we can just add the functionality now, and then retro fit the buttons into the combined ellipses button. I opened another issue for that work.
https://github.com/chef/automate/issues/1331
