### ISSUE TITLE
Backend v1/v2 conditional logic 

### ISSUE THREAD

**Issue by susanev** [chef/automate#2729]
##### auth middleware in the gateway #3272 
- [x] delete the [v1 implementation of GRPCAuthorizationHandler](https://github.com/chef/automate/blob/master/components/automate-gateway/gateway/middleware/authv1/authv1.go)
- [x] update dependent tests
- [x] remove the [v1 introspection generation code](https://github.com/chef/automate/tree/master/components/automate-gateway/api/authz/pairs) (this might already be done in [this v1 API card](https://github.com/chef/automate/issues/2724))
- [x] if there's time, remove the [switching mechanism](https://github.com/chef/automate/blob/master/components/automate-gateway/gateway/middleware/auth_interceptor.go#L40-L99) since we'll only have one way to authorize now
- [x] double check the service for any remaining v1/v2 conditional handling

##### authz-service #2739
- [x] remove the [interceptor](https://github.com/chef/automate/blob/master/components/authz-service/server/v2/authz.go#L269-L312)
- [x] remove [version switch](https://github.com/chef/automate/blob/master/components/authz-service/server/v2/authz.go#L30) from authz server state (don't forget the [switching channel](https://github.com/chef/automate/blob/master/components/authz-service/server/v2/authz.go#L314))
- [x] drop the [v1 server implementation](https://github.com/chef/automate/tree/master/components/authz-service/server/v1)
- [x] drop the [v1 storage implementation](https://github.com/chef/automate/blob/master/components/authz-service/storage/v1) 
- [x] determine what [v1 OPA unit tests](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa_test.go) and [v1 OPA internal tests](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa_internal_test.go) (if any) can be ported to their v2 counterparts
- [x] remove from OPA: 
     - [x] [v1 cache](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa.go#L27)
     - [x] [v1 partial evaluation result](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa.go#L32)
     - [x] v1 authorization checker [IsAuthorized](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa.go#L269)
     - [x] v1 introspection helper [FilterAuthorizedPairs](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa.go#L338)
     - [x] v1 OPA [helpers](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/opa.go#L240)
     - [x] [v1 introspection rego](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/policy/introspection.rego) and [v1 authorization rego](https://github.com/chef/automate/blob/master/components/authz-service/engine/opa/policy/authz.rego)
     - [x] [v1 example policies](https://github.com/chef/automate/tree/master/components/authz-service/engine/opa/example)
- [ ] ~add a migration that drops the `policies` table (assuming the force-upgrade migrations are already in-place)~ will be fixed in #3480 but removed from this epic
- [x] double check the service for any remaining v1/v2 conditional handling

##### teams-service #3273 
- [x] rename team user_ids to membership_ids (https://github.com/chef/automate/issues/3075)
- [x] on [authn-service](https://github.com/chef/automate/blob/master/components/authn-service/server/server.go#L170), [local-user-service](https://github.com/chef/automate/blob/master/components/local-user-service/server/server.go#L45), [automate-gateway](https://github.com/chef/automate/blob/master/components/automate-gateway/gateway/clients.go#L96), and [automate-deployment](https://github.com/chef/automate/blob/master/components/automate-deployment/pkg/usermgmt/client/client.go#L47), swap the v1 teams client for a v2 teams client
- [x] drop the [v1 server ](https://github.com/chef/automate/tree/master/components/teams-service/server/v1)
- [x] double check the service for any remaining v1/v2 conditional handling

##### authn-service #3274 
- [x] migrate v1 tokens to v2 format (should be done by: https://github.com/chef/automate/issues/2741)
- [x] double check the service for any remaining v1/v2 conditional handling

## Definition of Done
- [x] the backend no longer has conditional logic for switching between IAM v1 and v2
- [x] comments about v1 and v2 are removed from all backend services

**Comment by susanev** [comment]
more context in #1888

**Comment by susanev** [comment]
and #1890
