### ISSUE TITLE
remove IAM v1 code from teams-service

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2740]
## Goal

Remove backend v1/v2 conditional logic from the teams-service.

Note: this work should be split into a few PRs.

## Definition of Done
- [ ] drop the [v1 team API](https://github.com/chef/automate/tree/master/api/interservice/teams/v1)
- [ ] on [authn-service](https://github.com/chef/automate/blob/master/components/authn-service/server/server.go#L170), [local-user-service](https://github.com/chef/automate/blob/master/components/local-user-service/server/server.go#L45), [automate-gateway](https://github.com/chef/automate/blob/master/components/automate-gateway/gateway/clients.go#L96), and [automate-deployment](https://github.com/chef/automate/blob/master/components/automate-deployment/pkg/usermgmt/client/client.go#L47), swap the v1 teams client for a v2 teams client
- [ ] drop the [v1 server ](https://github.com/chef/automate/tree/master/components/teams-service/server/v1)
- [ ] double check the service for any remaining v1/v2 conditional handling
- [ ] migrate v1 teams to v2 format ([issue](https://github.com/chef/automate/issues/1144))
