### ISSUE TITLE
remove v1 teams gateway APIs

### ISSUE THREAD

**Issue by bcmdarroch** [chef/automate#2865]
## TODO
- [ ] delete team protos
- [ ] replace v1 API paths with v2
```
./src/app/components/settings-sidebar/settings-sidebar.component.html:25:    
<app-authorized  #teams [allOf]="['/auth/teams', 'get']">

./src/app/modules/team/team-management/team-management.component.html:43:              
<app-authorized [allOf]="['/auth/teams', 'post']">

./src/app/modules/team/team-management/team-management.component.html:95:            
<app-authorized [allOf]="['/auth/teams', 'post']">

./src/app/modules/team/team-management/team-management.component.html:103:            
<app-authorized not [allOf]="['/auth/teams', 'post']">
```
- [ ] fix/port affected tests
