### ISSUE TITLE
Acceptance Test force-upgrade merge

### ISSUE THREAD

**Issue by susanev** [chef/automate#2978]
#### Batch 1 @blakestier 
- [x] [swap teams v1 client to v2 client in automate-deployment](https://github.com/chef/automate/issues/2876)
- [x] [Force Upgrade teams-service](https://github.com/chef/automate/issues/2926)
- [x] [swap teams v1 client to v2 client in authn-service](https://github.com/chef/automate/issues/2861)
- [x] [Investigate NATS gateway failure](https://github.com/chef/automate/issues/2930)
- [x] [Move all IAM v2 migrations into service startup migrations](https://github.com/chef/automate/issues/2720)
- [x] [remove IAM v1 code from automate-gateway](https://github.com/chef/automate/issues/1890)

#### Batch 2 @msorens 
- [x] [swap teams v1 client to v2 client in local user service](https://github.com/chef/automate/issues/2857)
- [x] [UI: removal of IAM version conditional logic](https://github.com/chef/automate/issues/2722)
- [x] [remove IAM v1 code from teams-service](https://github.com/chef/automate/issues/2740)
- [x] [remove v1 tokens gateway APIs](https://github.com/chef/automate/issues/2867)
- [x] [remove v1 users gateway APIs](https://github.com/chef/automate/issues/2866)
- [x] [remove v1 policies gateway APIs](https://github.com/chef/automate/issues/2868)

#### Batch 3 @tylercloke 
- [x] [remove v1 teams gateway APIs](https://github.com/chef/automate/issues/2865)
- [x] [deal with introspection](https://github.com/chef/automate/issues/2950)
- [x] [integration test: V1 -> force-upgrade to V2](https://github.com/chef/automate/issues/2914)
- [x] [Ingest access legacy migration](https://github.com/chef/automate/issues/2987)
- [x] [integration test: latest V2 with no legacy policies -> force-upgrade to latest V2](https://github.com/chef/automate/issues/2916)
- [x] [integration test: latest V2 with legacy policies -> force-upgrade to latest V2 with legacy policies](https://github.com/chef/automate/issues/2917)

#### Batch 4 @bcmdarroch 
- [x] [Remove v1 storage from authz service](https://github.com/chef/automate/issues/3065)
- [x] [Remove v1 server code](https://github.com/chef/automate/issues/3129)
- [x] [Port any necessary V1 OPA tests to V2](https://github.com/chef/automate/issues/3066)
- [x] [Change chef-managed editor and viewer roles and infra legacy policy](https://github.com/chef/automate/issues/2710)
- [x] [Remove admin-token references](https://github.com/chef/automate/issues/1886)
- [x] [[Automate-2950] port introspection, wave two](https://github.com/chef/automate/issues/3050)
