### ISSUE TITLE
compliance reporting export improvements

### ISSUE THREAD

**Issue by vjeffrey** [chef/automate#381]
# User Story

The compliance reporting export endpoint is good, but not quite good enough.

- [x] we don't correctly format the output (https://github.com/chef/automate/issues/195)
- [x] we ignore the start time when we gather the reports, meaning ppl can't widdle down their report size to smaller date chunks (https://github.com/chef/automate/issues/531) - https://github.com/chef/automate/pull/639
- [x] after collecting the list of report ids, we get each report, one by one, from elasticsearch, sometimes leading to a too many connections error (https://github.com/chef/automate/issues/251)
- [x] add a new endpoint that can be used to gather ids of all reports in the system, which is not limited by pagination - https://github.com/chef/automate/pull/640

# Definition of Done
Compliance reporting export is better!

**Comment by vjeffrey** [comment]
Note: if we decide to respect start_time on reporting export, we will need to ensure that the ui either
- implements changes that will make it easy for the user to say "give me latest report for all nodes" or "give me latest report for nodes that landed in the last 24 hrs/48 hrs/week/month"
OR (easier) the UI does not send a start time to that endpoint, leaving the ui functionality as is for now and enabling the start time functionality for api users

**Comment by jonong1972** [comment]
The first bullet point would be awesome, but that would mean in the UI we would have to re-visit the date picker in the search field to allow date ranges.  Because right now, I am assuming the download reflects the search field, which would reflect the date? (which currently is only 24 hours)  
But doing this would probably mean solving a the bigger problem of allowing date ranges in search.

**Comment by vjeffrey** [comment]
ah, i was talking about the time range for _just the export_ . Applying a time range for everything could have a significant performance impact. We've modeled things around the idea that we only show today's reports

**Comment by jonong1972** [comment]
Yup.  Thats why the first bullet point would be awesome, but probably not for the near term.

**Comment by jonong1972** [comment]
Because now, that since we allow the user to filter by the search box and it would reflect in the export.  Would be weird to were they would have filters within the search box, and then another place to do a date range - but cannot view that date range within the GUI.
