### ISSUE TITLE
UI Improvements for Edit View

### ISSUE THREAD

**Issue by himanshi-chhabra** [chef/automate#4873]
## Describe the bug

- [x] - In the Environment list/ Databag list/ client list page height of the search icon is overlapping the search bar border.
- [x] - In Environment/ Databag/ Client/ Role details page update the CSS of tabs.
- [x] - CSS of create and edit pop-up of Databag as it overrides all other pop-ups CSS.
- [x] - Search buttons are not keyboard accessible.
- [x] - After opening create environment Deleted dropdown CSS gets override.
- [x] - In Create Environment, disable create button if a name already exists.
- [x] - In create Environment, change the border color of the text-field when focused.
- [x] - In the edit environment, change the border size of the label.
- [x] - In Environment details : 

	1. Add no preview image in attributes tab if no JSON available
	2. Change border-size of details box  1px.
	3. When we click the button of edit or expand we have to click twice then the pop-up visible. need to update this.
	4. Edit, Expand, collapse buttons are not keyboard accessible.

- [x] - While creating the first Databag item I do not see the data bag item immediately.
- [x] - [#4878](https://github.com/chef/automate/issues/4878)
- [x] - Edit databag item -> open item details -> cursor is always pointer
- [x]  - Databag should be referred as "Data Bag" in the UI

Aha! Link: https://chef.aha.io/epics/SH-E-354

**Comment by kalroy** [comment]
FIxed the following issues:

- In the Environment list/ Databag list/ client list page height of the search icon is overlapping the search bar border.
- CSS of create and edit pop-up of Databag as it overrides all other pop-ups CSS.
- Search buttons are not keyboard accessible.
- In Create Environment, disable create button if a name already exists.
- In create Environment, change the border color of the text-field when focused.
- Edit databag item -> open item details -> cursor is always pointer

in the PR #4888
