### ISSUE TITLE
Migrate Chef Server users to Automate

### ISSUE THREAD

**Issue by kalroy** [chef/automate#6130]
## User Story

As a Chef Server admin, I should be able to have the following functionalities:

- [ ] List all the users of a chef server
- [ ] Create their corresponding user in Automate
- [ ] Should be able to download the migrated user details
- [ ] Should have the ability to fetch users later after migration too
- [ ] Should be able to fetch the permission of every user
- [ ] Associate the users to IAM policies accordingly
- [ ] Associate the users to projects/teams for an organization

**Comment by kalroy** [comment]
Closing this EPIC as we are tracking user migration in #5548
