### ISSUE TITLE
Add IntrospectWithProjects and update all introspection APIs to use v2

### ISSUE THREAD

**Issue by susanev** [chef/automate#822]
## Overview

We do not currently have a way to introspect if a user has access to specific object based on projects. The scenario would be a user has `list` permissions on roles in multiple projects but not delete permission on some of the roles depending on which projects the roles were in. Only the roles that the user has list access to will show up, but we need a way of checking per specific object based on projects.

Also, does whether or not the user has _any_ access to non-object based enpoints like listing roles work in the projects world? Double check that that code is functioning as intended.

Lastly, we should add v2 endpoints for any v1 endpoints we want to keep then update the UI to conditionally use v1 vs v2.0 vs v2.1 depending on which of the introspection endpoints are correct for each.

Similar to what was just recently done for users (PR-279), introspection is the last API that should be also exposed on the v2 endpoint path. This includes:

* IntrospectAll
* IntrospectSome
* Introspect
* IntrospectAllProjects

The last one, `IntrospectAllProjects`, should only have a v2 endpoint so it should be removed from v1.

This work will include updating the API only; no changes in the UI.

## Subtasks

- [ ] Add new GRPC function `IntrospectWithProjects` or something similar
- [ ] Update all paths on the backend
- [ ] Update everything in automate-ui
- [ ] Update the tests

**Comment by sdelano** [comment]
I'm trying to unpack the scenario above and understand other scenarios as well. The scenario in the description says:

* a user has `list` permissions on a set of items
* the same user has `delete` permissions on a subset of those items

When I go to the page that lists all the items, I should only see the delete options for the items that I have delete permissions on. Right now, I see the delete option for all the items that I have list permissions on.

Right now, the end effect is that if I click on the delete button I'll get a permissions error that I can't perform the action.

The desired experience is that the delete button never appears (or is inactive) because I don't have that permission. To achieve this, we need a new type of introspection API.

Is this correct?

**Comment by susanev** [comment]
this work has been deprioritized, so closing.
