### ISSUE TITLE
IAM v2.1 Beta Documentation Updates

### ISSUE THREAD

**Issue by susanev** [chef/automate#825]
## Overview
Update the current IAMv2 Beta Documentation to include Projects: IAM and node resources. Ideally, this will include adding content to already existing pages and not require creating additional pages. @mjingle should be involved in planning and review.

see [comment](https://github.com/chef/automate/issues/825#issuecomment-534764266) from @sdelano for details on auth process.

_Note: Docs team is not available until 10/09 to contribute._

## Subtasks
_Note: When everything is ready for docs, it should be a single pr._

- [x] Overview @msorens (PR #1731)
- [x] User's Guide @blakestier @bcmdarroch #1838 
- [x] API Reference @msorens (PR #1813)

#### Overview

1. Add projects information including updating the IAM v2 diagram (@susanev will update diagram)
2. Explain how (unassigned) works; explain that all resources will land in unassigned after users upgrade to beta
3. Add the project admin role to the role table
4. Update all screenshots

#### User Guide

1. Add projects information to the user's guide, including adding additional sections on ingested infra nodes, compliance nodes, and events
2. to do this, walk through [the part 2 demo of this issue](https://github.com/chef/automate/issues/797) as a way to introduce users to the concept of projects
3. Update all screenshots

#### API Reference

1. Edit information in the API reference to include projects information (projects CRUD API, adding projects to IAM resources, rules API)
2. Describe the project admin role in the role table
3. Include the new v2 endpoints for users, team, and tokens.

### Important Details

1. Explain users need to update to audit cookbook 7.5+ to have all the fields (chef server, org, environment, role, policygroup, policyname) available to them in the compliance reports; using an older cookbook will only have environment and role in the compliance reports. Any old reports will only have the environment and role.
2. In order to use the Chef Tags attribute for moving compliance nodes into projects they need to be using audit cookbook 7.5+ we should prolly call this out in project docs because we have already had a customer have this issue
3. Workflow has Projects, work with the docs team to maybe update Workflow docs to specify that they are Workflow Projects, may need to indicate somewhere that Workflow projects are different than IAM projects (work with docs team on this)
4. Explain difference between the operators EQUALS and MEMBER_OF in rule conditions. Emphasize that all rule conditions must be true for the rule to apply. (for example: the conditions chef_org EQUALS project1 and chef_org EQUALS project2 contradict each other. the operator MEMBER_OF should be used instead)
5. Explain difference between policy projects and statement projects
6.  Token permissions: either do not delete the ingest legacy policy, or need to move the members of it to the new ingest policy

## Resources
- [iam v2.1 pre-beta documentation](https://gist.github.com/sdelano/ef3dd71e7445d28617924d8c8e2914da) by @sdelano 
- [IAM version differences](https://docs.google.com/document/d/1Ej5st1eaZ5hn13g4hVhVFvwlE-cfr0OcG_tKdReddj8/edit) by @msorens

**Comment by nfisher-chef** [comment]
The Auth triad and the Docs team met today to discuss how we would like to proceed for documentation for IAM v2.1 Beta. To summarize the meeting, the Auth team can get started on drafting IAMV2.1 Docs. The Doc team will be able to start working on this October 9.

**Comment by sdelano** [comment]
@chef/auth-team - there was some discussion about having this work consist of 3 PRs to parallelize the work on each of the the pages. We can still accomplish that, but the request from the docs team is that the draft changes that we create are all contained in a single source for them to editorialize into the final docs. Here's the plan:
- we'll create an integration branch for the docs changes: `iam-beta-21-docs`
- each parallel PR will be into that branch, not `master`
- we'll create a final PR of the integration branch into `master` from which @mjingle can complete the final edits 

I mentioned *draft* above. Not in the sense that we'll mark the pages as drafts so they don't show up in the docs but in the sense that we're providing the meat of the content before the docs team makes the finishing touches with full editorial control.

**Comment by blakestier** [comment]
This isn't actually enforced, though: if they have multiple EQUALS statements, the behavior will be the same as if they had a single one with multiple values in the MEMBER OF array. Do we care? Given that we don't edit rules really, it's almost helpful to have them in different statements (in my experience)

> Emphasize that all rule conditions must be true for the rule to apply. (for example: the conditions chef_org EQUALS project1 and chef_org EQUALS project2 contradict each other. the operator MEMBER_OF should be used instead)

**Comment by msorens** [comment]
@blakestier It is enforced, once you include the secret phrase "within a single rule"; in fact I just reviewed a PR from Lance that showed that very thing (https://github.com/chef/automate/blob/ec1e609d602d09e3bf59e13662a66ab21435ca40/components/nodemanager-service/pgdb/project_update.go#L189-L275).

Also, not clear which parts you mean by saying "statements". There are only rules and conditions, no statements.

All conditions are conjunctive; all rules are disjunctive.
Thus, within a single rule all conditions have to be true for the rule to apply.
But only a single rule has to apply for the projects to be assigned.

**Comment by blakestier** [comment]
That's what I would expect but was not seeing this in practice 🤔
