### ISSUE TITLE
_Flip the Switch_ so that IAM v2.1 beta happens on upgrade

### ISSUE THREAD

**Issue by susanev** [chef/automate#829]
## Overview

Any code changes that need to happen so that projects with IAM resources, ingested nodes, (and node integrations, unsure if this will make it in) are included in the upgrade to v2.

This will include the following:
* On `upgrade-to-v2` it should upgrade to 2.1 not 2.0
* Anyone on 2.0 should be upgraded to 2.1 on their next update
* Remove the 2.0 release environments

We are working out of a feature branch `flip-the-switch` so please open PRs against master as a draft, see the tests pass, switch the PR to against `flip-the-switch` and then undraft.

## Sub-tasks
- [x] remove Beta 2.1 flag from upgrade API, `upgrade-to-v2` performs old v2 upgrades (migrates legacy policies, etc) **and** turns on v2.1 project functionality @tylercloke https://github.com/chef/automate/pull/1861
- [x] on service start-up, if customer is on v2, auto upgrade to v2.1 @tylercloke https://github.com/chef/automate/pull/1899
- [x] reset all IAM objects to have empty project arrays #1942 @tylercloke 
         There may still be some default projects in some IAM objects lurking in customer databases. We need to write a migration that resets all IAM objects to have empty project arrays prior to releasing the --beta2.1 flag.

**Comment by susanev** [comment]
moved a few of these not critical for 2.1 release subtasks to after release as discussed in standup today #1877
