### ISSUE TITLE
add db_id as primary key to auth databases

### ISSUE THREAD

**Issue by susanev** [chef/automate#832]
## Overview

We'd like to keep the primary IDs of our databases immutable and safe from users.

Currently, roles and projects have a db_id column, but only roles uses it as the primary ID. Policies, teams, and tokens all use the id as the primary ID, and they have no db_id column.

Let's make our databases consistent, with each resource table (policies, roles, projects, teams, tokens) using an integer db_id as the primary ID. All relational tables should be updated as necessary.

Use db_id internally.

## Subtasks
- [x] update tokens table
- [x] update teams table
- [x] update members
- [x] add db_id to policy table and change related tables/constraints
- [x] add db_id to projects table and modify related tables/constraints
  - [x] `iam_projects <-> iam_[staged_]project_rules` #862 
  - [X] `iam_projects <-> iam_role_projects` #878
  - [x] `iam_projects <-> iam_policy_projects` #898 
  - [x] `iam_projects <-> iam_statement_projects` #905
  - [x] flip `PRIMARY KEY` constraint of `iam_projects` from `id` to `db_id` #913  
- [x] add db_id, policy_id to iam_statements/ remove iam_policy_statements #855
- [x] use statement db_id as key in `iam_statement_projects` also in #913
- [x] use `role` db_id in `iam_statements` #942
- [x] Make all columns that should have NULL constraint have NULL constraint #1052
The last one overlapped #820-- related content below:
- [x] Make `strict` use consistent in [*_db_id functions](https://github.com/chef/automate/pull/942#discussion_r306507012) #1055 

### Bonus tasks (read: I'm tired of this -- @srenatus )
- [x] Replace `iam_projects`'s `projects` column (type `text[]`) with a `iam_projects_projects` table having two columns of `db_id` (`INTEGER`) for properly assigning a project's projects
  - _Discussed in standup 07/25: we'd like to just drop the column today; and re-introduce it (properly) when we need the feature._
  - #1109 
- [x] Remove the `id` column of `iam_statements` and `iam_members`. They're internal artifacts we no longer need.
  - [x] `iam_members`: #1074 
  - [x] `iam_statements` **RFR** #1120

Note: there might already be statements using roles and that means there might be roles in statements that are not valid IDs, so just adding the constraint could cause migrations to fail.

solution: on migration, drop invalid roles if it's the only role in the statement and there are no actions then drop the statement entirely. we might also add a constraint that drops policies with empty statements

though it's not the nicest UX, we are in beta.

### Related issue: [Logically propagate deleted projects within policies](https://chefio.atlassian.net/browse/A2-797)
When a policy loses its last statement because all the statements projects were deleted, the policy should be dropped.

### Potential solution
We could add a constraint or trigger to the policies table that drops policies with empty statements, which could be triggered by any of the various actions that render a policy useless

**Comment by srenatus** [comment]
I'm quite sick of this, but a statement's **role** also doesn't use the _role_'s `db_id`, but its ID:

```
chef_authz_service=# \d iam_statements;
                              Table "public.iam_statements"
  Column   |    Type    |                           Modifiers
-----------+------------+----------------------------------------------------------------
 id        | uuid       | not null
 effect    | iam_effect | not null
 actions   | text[]     |
 resources | text[]     |
> role     | text       |
 db_id     | integer    | not null default nextval('iam_statements_db_id_seq'::regclass)
 policy_id | integer    |
Indexes:
    "iam_statements_pkey" PRIMARY KEY, btree (db_id)
    "iam_statements_id_key" UNIQUE CONSTRAINT, btree (id)
Foreign-key constraints:
    "iam_statements_policy_id_fkey" FOREIGN KEY (policy_id) REFERENCES iam_policies(db_id) ON DELETE CASCADE DEFERRABLE
Referenced by:
    TABLE "iam_statement_projects" CONSTRAINT "iam_statement_projects_statement_id_fkey" FOREIGN KEY (statement_id) REFERENCES iam_statements(id) ON DELETE CASCADE DEFERRABLE

chef_authz_service=# \d iam_roles;
                               Table "public.iam_roles"
 Column  |      Type       |                         Modifiers
---------+-----------------+-----------------------------------------------------------
> db_id  | integer         | not null default nextval('iam_roles_db_id_seq'::regclass)
 id      | text            | not null
 name    | text            | not null
 type    | iam_policy_type | not null default 'custom'::iam_policy_type
 actions | text[]          |
Indexes:
    "iam_roles_pkey" PRIMARY KEY, btree (db_id)
    "iam_roles_id_key" UNIQUE CONSTRAINT, btree (id)
Referenced by:
    TABLE "iam_role_projects" CONSTRAINT "iam_role_projects_role_id_fkey" FOREIGN KEY (role_id) REFERENCES iam_roles(db_id) ON DELETE CASCADE

```
