### ISSUE TITLE
IAM v2.1 Ingest mapping rules on projects

### ISSUE THREAD

**Issue by susanev** [chef/automate#854]
## Overview

Users are able to define ingest rules and conditions for individual projects. Note, that [Enforce IAM project filtering for nodes list, search agg data, node details](https://chefio.atlassian.net/browse/A2-320) needs to be completed before users will be able to apply the ingest rules to their ingesting nodes.

[Video](https://drive.google.com/file/d/16h8gcw-UOiKRqRNvbf29sMv-EL33DOxo/view?usp=sharing)

## Subtasks
- [x] Full-page design stencil component @tarablack01 #560 
- [x] Projects list page ui @scottopherson #511 
- [x] Projects detail page ui @tarablack01 #736
- [x] Projects create/update ingest rule ui @tarablack01 #736
- [x] Fix bug with subheading wrapping and pushing the iframe down too far @tarablack01 #560 
- [x] Follow-on pr with some clean up related to #736 @msorens #1020 
- [x] Add URL fragments for projects (#rules and #details), similar to teams (#users and #details) and policy (#definition and #members). @msorens #1194
- [x] [Connect APIs to UI components on project detail pages](https://app.zeplin.io/project/5ba808703eb54372d860c737/dashboard?tag=list-view&tag=projects) (NOTE: all requests are already wired in ngrx store)
    - [x] Get Project Rules / Ingest Rules table @blakestier @bcmdarroch #1156 
    - [x] Delete Rule / Delete rule button and modal @blakestier @bcmdarroch #1156 
- [x] Connect APIs to UI components for [create ingest rules](https://zpl.io/anydmek) and [update ingest rules](https://zpl.io/aMWKm1N)
    - [x] Create Rule / Create Rule button and Create Rule modal @blakestier @bcmdarroch #1156 
    - [x] Update Rule / Update Rule button and Update Rule modal @blakestier @bcmdarroch #1156
- [x] [Connect APIs to UI components for project list page](https://app.zeplin.io/project/5ba808703eb54372d860c737/dashboard?tag=list-view&tag=projects)
    - [x] Update All Projects / Update Projects button and modal
    - [x] Project Update Percentage / Update Projects button
    - [x] Project Rule Edits Status / Ingest Rules column @msorens #1250
    - [x] Project Update Status / Project Update Status button @msorens #1309
    - [x] Delete Project / Delete Project button and modal
    - [x] Connect APIs to UI components for stop project update @msorens #1309 
    - [x] Stop Project Update / [Stop Project Update button](https://zpl.io/2GG9m9m) and [Stop Project Update modal](https://zpl.io/2GG9m9m)
    - [x] Wire up back-end of "cancel update" @jaym @msorens #1502 

 ## Designs

[Zeplin](https://app.zeplin.io/project/5ba808703eb54372d860c737/dashboard?seid=5cb7bd42bc7d832f0b3f7ac0)

#### Ingest Rules
* _No rules_: Only applicable for projects with zero ingest rules
* _Edits pending_: If at least one ingest rule in the project has edits pending, or a rule in the project has been deleted since the last update
* _Applied_: If all ingest rules in the project are applied

#### Project Update Status
* _OK_: No update needed
* _Needs updating_: Needs to be updated because there are ingest rules edits pending, or because of stopping the update early or because of failures (failure communication will come in a later story)
* _Updating..._: An update is currently in progress

#### Edits
* _Edits pending_: An edit has happened since the last update or because there has been no update
* _Applied_: All ingest rules will be applied to newly ingested resources

#### Projects List Page

* Add secondary _Update Projects_ button
* Remove _Type_ column, all projects will be _Custom_
* Add an _ID_ column
    * Note: All settings list pages will be updated to have an _ID_ column in the future
* Add an _Ingest Rules_ column
    * Options: _No rules_, _Edits pending_, _Applied_
* Add a _Project Update Status_ column
    * Options: _OK_, _Needs updating_, _Updating..._

#### Update Projects Button
* Disabled with label _Update Projects_ when all projects have a project update status of OK
* Disabled with label _Updating Projects (<n>%)..._ when at least one project has a project update status of Updating...
* Enabled with label _Update Projects_ when at least one project has a project update status of _Needs updating_ and a current update is not in progress
* When updating is in progress a _Stop Updating Projects_ tertiary button should be displayed next to the disabled updating button
    * Note: The UX of both progress and canceling will be improved in the future
* When interacting with the button a confirmation modal is shown
    * Heading: _Update Projects?_
    * Message: _Updating projects will apply all pending edits and move ingested resources into the correct projects. This background process can take up to 12 hours to complete._
    * Primary button: _Update Projects_

#### Stop Updating Projects Button
* Tertiary
* Only visible with an update is in progress
* Includes confirmation...
    * Heading: _Stop Updating Projects?_
    * See Zeplin designs for the progress bar, and additional content
    * Message: _Stopping the project update early <strong>can not be undone</strong> and will leave some ingested resources in the wrong projects._
    * Primary destructive button: _Stop Updating Projects_

### Project Detail Page
* Add an _Ingest Rules_ tab to the left of the _Details_ tab

#### Empty State
When no ingest rules exist.. display the empty state pattern

* Message: _Create the first ingest rule to get started!_
* _Create Rule_ primary button

#### Create Rule
* Please leverage the already implemented designs of the full-page designs when adding members to a policy.
* On create the heading should be `<Project Name>: Rule`, but once they have entered characters in the rule name it should dynamically change to replace the text _Rule_ with whatever they name the rule
* For now, the only options in _Resource Type_ is _Node_ and _Event_.
* Condition column headers are _ATTRIBUTE_, _OPERATOR_, and _VALUE_ please use `text-transform` to achieve the uppercase letters so screen readers do not announce them as acronyms
    * Note: Once a resource type is selected the attribute column header should change to `ATTRIBUTE <resource type>`
* On create an initial condition should automatically be displayed. For additional conditions, the user will need to use the _Add Conditio_n button. Conditions should be added to the bottom.
* When more than 1 condition, the word _AND_ should be displayed at the end of the condition row (except for on the last condition)
* The only current operators are _equals_ and _member of_, _equals_ matches exactly, _member of_ the user specifies a comma-separated list.
* The delete button removes the condition without any kind of confirmation
* Save Rule should only become enabled when a name, resource type and values for at least one condition are provided.
* Help text...
    * equals: _Case sensitive, must match exactly._
    * member of: _Comma-separated list, at least one must match exactly._

#### Node Attributes
* Chef Organization (string)
* Chef Server (string)
* Environment (string)
* Chef Role (string[])
* Chef Tag (string[])
* Chef Policy Name (string)
* Chef Policy Group (string)

#### Event Attributes
* Chef Organization (string)
* Chef Server (string)

#### Edit Rule
* Same as _Create Rule_ but the _Resource Type_ input is disabled with different help text stating: _Resource types cannot be changed, create a new rule instead._
* The _Save Rule_ should only become enabled when a change is made.

#### Ingest Rules table
* Use the `chef-toolbar` with  always enabled primary _Create Rule_ button
* The table has 4 columns: checkboxes, _Name_, _Resource Type_, _Conditions_, and _Edits_.
    * Name displays the human-created name of the rule as a link
    * Resource Type displays Nodes or Events
    * Conditions displays the count of conditions associated with that rule, the number displayed first followed by a condition in the single case or conditions when more than one conditions.
    * Edits communicates either Edits pending when there are edits in staging or Applied when the edits have been applied.
* The control menu at the end of the row is dynamic If the rule is not currently being applied then it should have the option to _Delete Rule_.
* If any of the rules are in the _Edits pending_ state then text with a link back to projects should be displayed: _Edits pending, update projects to apply edits._

#### Delete Rule
* Only an option in the control menu when an update not in progress
* Includes a confirmation with the text `Deleting rule "<rule name>" <strong>can not be undone</strong>` and primary button Delete Rule
* Once deleted, the ingest rules state on the project list page should change to _Edits pending_ if it's not already that

#### What it looks like when we’re done
* Users' can navigate to individual projects and define the ingest mapping rules for their nodes.

#### Demo / Acceptance Criteria
* Navigate to _Settings_ > _Projects_
* Create a new project, which will navigate you to that project
* Create a node ingest rule, and an event ingest rule
* Edit rules, delete some rules, delete some conditions
* Test out the different states for updating projects
