### ISSUE TITLE
Stage Project Ingest Rule Changes and Update Events

### ISSUE THREAD

**Issue by tylercloke** [chef/automate#867]
# Problem

In order to facilitate updates of project ingest rules in a timely manner, we must apply them to the system in bulk. For the best user experience, we shall allow the user to stage these changes and persist them to the automate install before they take effect on the the incoming and historical data. This story defines that flow of information and the API that supports that use case.

# What it looks like when we're done

## Staging Changes

* A user should be able to stage changes to projects and rules in the system before applying them.

* If they leave their computer, get logged out, or their browser crashes, the changes they've staged should still be applicable

* If multiple users are staging changes, each user should be able to see the changes of the other user

* Staged changes should not be tied to a user, however, so we don't know who made what change

* All staged changes should be applied at the same time

## Applying Staged Changes

* Once a user is satisfied with the changes they've made to the projects and the rules, they should be able to apply the changes

* To effect the changes, the auth system needs to trigger an event in the event system that the project ingest rules have changed

### Waiting for success

* While the changes are taking effect, the user will see the status of the in-flight changes

* The auth system will wait for success messages from the in-flight changes in other services

* The user will receive a status via the user interface when the changes are complete

* A user will be unable to apply future changes without first canceling the in-flight changes

### Staging More Changes

* While changes are in flight, a user can continue to stage future changes to the ingest rules

* Before applying these rules, a user must first cancel the in-flight changes

# Subtasks

- [x] new table to persist desired changes to project rules
- [x] YJ Projects: Apply API
- [x] API to apply changes
- [x] API to fetch a project's rules including staged changes
- [x] API to fetch rules diff
- [x] API to check the state of currently running background job of applying rules
- [x] API to cancel currently running background job of applying rules
- [x] refactor UpdateRule
- [x] refactor DeleteRule
- [x] Refactor Rules API integration tests to include staging APIs @bcmdarroch #870 
- [x] Rule object contains staged or applied status @tylercloke 
- [x] Project API returns rule edits status @tylercloke https://github.com/chef/automate/pull/925

## Subtask: Project API returns rule edits status

We need to be able to show the rule edits status for a given project. This value appears in the Ingest Rules column of the Project List page.

There are three possible statuses:

Edits pending (see https://zpl.io/bJp9KvD)

* If any of the project’s rules have staged changes

No rules (see https://zpl.io/bA7ZvqP)

* If the project has no staged or applied rules

Applied (see https://zpl.io/2GG9m9m)

* If none of the project’s rules have staged changes

After team discussion:

Staged rules, job running (edits pending/needs update)
No rules, job running (no rules/OK)
No staged rules, job running (Applied/Updating)

**Comment by srenatus** [comment]
> susanev changed the pipeline from 👨‍👩‍👧 Review to 🤺 Acceptance Testing in Automate Auth 17 days ago

hrmm I feel like this has been tested before my turn began _last week_? :thinking:

Well, I'll click around a bit in the UI. Haven't done that before.

**Comment by srenatus** [comment]
Hrm rules still aren't persisted. I don't believe this is ready yet.

**Comment by srenatus** [comment]
@bcmdarroch informed me the UI stuff is happening in a different story... I'll add that to my TODO list for acceptance testing tomorrow.

**Comment by srenatus** [comment]
Further discussed this with @bcmdarroch... we should have some automated tests for these API-only subtasks. I'll review them briefly tomorrow and push the card forward.

**Comment by srenatus** [comment]
https://github.com/chef/automate/issues/1130 _seems related to this_ -- but that could just be a UI thing
